theme: jekyll-theme-cayman
title: Neural Bidirectional Texture Function Compression and Rendering
description: A paper from Traverse Research which presents a solution using Neural Networks to compress and render materials from BTF data. 